"""type and status

Revision ID: fc74e69e6eee
Revises: 766e2484b934
Create Date: 2023-11-07 19:58:04.516531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc74e69e6eee'
down_revision = '766e2484b934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('Application', 'Phone', 'Manager', 'HR', 'Technical', 'Offer', 'Finish', 'Default', name='interviewtypeenum'), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('Accepted', 'Pending', 'Rejected', 'Default', name='interviewstatusenum'), nullable=True))
        batch_op.drop_column('interview_status')
        batch_op.drop_column('interview_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_type', mysql.ENUM('Application', 'Phone', 'Manager', 'HR', 'Technical', 'Offer', 'Finish', 'Default'), nullable=True))
        batch_op.add_column(sa.Column('interview_status', mysql.ENUM('Accepted', 'Pending', 'Rejected', 'Default'), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
